### PR TITLE
chore: Clean up duplicate user input prompt string of game saves

### PR DESCRIPTION
**Pull request by eric15342335**
File I/O:
* `file_io.cpp` 192-197 has duplicate strings (that appears on `main.cpp` too) which can be converted into a `const string` global variable `USER_SAVE_OPTION_PROMPT` stored in `file_io.h`

* Define user game save input option globally in `USER_SAVE_OPTION` class to improve maintainability

UI/UX:
* Fix inconsistency of newline `\n` character found between `main.cpp` and `file_io.cpp` user input prompt string

### CODE REVIEW

**Comment by eric15342335** [comment]
~wtf~ why the tests are failing

**Comment by eric15342335** [comment]
`Cannot reproduce....`

**Comment by eric15342335** [comment]
Not necessary (`DO NOT MERGE`) since the tests are failing anyway...

**Comment by eric15342335** [comment]
Still fails..... :( 😿

**Comment by eric15342335** [comment]
...

**Review by comet13579 — APPROVED** [review]

**Review by comet13579 — APPROVED** [review]

**Pull request merged**
